"""
Ensemble Turf Detection (Logical AND)

This script executes the finalized Hyper-Sensitive Ensemble workflow.
It takes the masks generated by the U-Net detector (at high recall threshold 0.1)
and the Grounding DINO + SAM pipeline, and performs a strict Logical AND.
This guarantees that only pixels verified by BOTH architectures are retained
in the final output.
"""
import argparse
import os
import cv2
import numpy as np

def run_ensemble(unet_mask_path, sam_mask_path, out_mask_path, image_path=None, exg_thresh=10):
    os.makedirs(os.path.dirname(out_mask_path), exist_ok=True)
    
    # Load both masks as grayscale
    unet_mask = cv2.imread(unet_mask_path, cv2.IMREAD_GRAYSCALE)
    sam_mask = cv2.imread(sam_mask_path, cv2.IMREAD_GRAYSCALE)
    
    if unet_mask is None or sam_mask is None:
        raise FileNotFoundError(f"Could not load one of the masks: {unet_mask_path}, {sam_mask_path}")
        
    if unet_mask.shape != sam_mask.shape:
        # Resize SAM mask to match U-Net mask just in case
        sam_mask = cv2.resize(sam_mask, (unet_mask.shape[1], unet_mask.shape[0]), interpolation=cv2.INTER_NEAREST)
        
    # The core Ensemble logic: Strict Intersection
    ensemble = np.bitwise_and(sam_mask, unet_mask)
    
    # Optional ExG Vegetation Sanity Filter
    if image_path:
        img = cv2.imread(image_path)
        if img is not None:
            # OpenCV loads as BGR
            b = img[:, :, 0].astype(np.int32)
            g = img[:, :, 1].astype(np.int32)
            r = img[:, :, 2].astype(np.int32)
            
            # Excess Green Index (ExG) = 2*G - R - B
            exg = 2 * g - r - b
            veg_mask = (exg > exg_thresh).astype(np.uint8) * 255
            
            # Resize veg_mask to match ensemble just in case
            if veg_mask.shape != ensemble.shape:
                veg_mask = cv2.resize(veg_mask, (ensemble.shape[1], ensemble.shape[0]), interpolation=cv2.INTER_NEAREST)
                
            ensemble = np.bitwise_and(ensemble, veg_mask)
            print(f"Applied ExG Vegetation filter (thresh={exg_thresh})")
        else:
            print(f"Warning: Could not load image from {image_path} for ExG filtering.")
            
    cv2.imwrite(out_mask_path, ensemble)
    print(f"Ensemble mask saved to: {out_mask_path}")
    return ensemble

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--unet_mask", required=True, help="Path to the U-Net predicted mask (run with --thresh 0.1)")
    ap.add_argument("--sam_mask", required=True, help="Path to the SAM zero-shot mask")
    ap.add_argument("--out_mask", required=True, help="Path to save the final ensemble mask")
    ap.add_argument("--image", default=None, help="Optional path to raw image for Excess Green index filtering")
    ap.add_argument("--exg_thresh", type=int, default=10, help="Excess Green Index threshold")
    args = ap.parse_args()
    
    run_ensemble(args.unet_mask, args.sam_mask, args.out_mask, args.image, args.exg_thresh)
